docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Intro: intro.md
    - Reference:
      - 'Routing': routing.md
      - 'Controllers': controllers.md
      - 'Modules': modules.md
      - 'Listeners': listeners.md
      - 'Default Services': services.md
    - Migration:
      - 'Version 2 to Version 3': migration/v2-to-v3.md
site_name: zend-mvc-console
site_description: Zend\Mvc\Console
repo_url: 'https://github.com/zendframework/zend-mvc-console'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
