docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - 'Routing': routing.md
      - 'Controllers': controllers.md
      - 'Modules': modules.md
      - 'Listeners': listeners.md
      - 'Default Services': services.md
    - Migration:
      - 'Version 2 to Version 3': migration/v2-to-v3.md
site_name: zend-mvc-console
site_description: 'Integration between zend-mvc and zend-console.'
repo_url: 'https://github.com/zendframework/zend-mvc-console'
extra:
    show_special_homepage: True
